### ISSUE TITLE
Build details not showing up for LARGE build output.

### ISSUE THREAD

**Issue by davidx** [basho-labs/thumbs#55]
Final build details on pull requests with build steps that generate a lot of data, the total comment body becomes too large for github to handle.  happens both succeeding as well as failing builds.  example : https://github.com/basho/riak_kv/pull/1560

```
2016-12-03 09:31:00 - Octokit::UnprocessableEntity - PATCH https://api.github.com/repos/basho/riak_kv/issues/comments/264651763: 42
2 - Validation Failed
Error summary:
  resource: IssueComment
  code: custom
  field: body
  message: body is too long (maximum is 65536 characters) // See: https://developer.github.com/v3/issues/comments/#edit-a-comment:
        /usr/local/lib/ruby/gems/2.3.0/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete'
        /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.10.0/lib/faraday/response.rb:9:in `block in call'
        /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.10.0/lib/faraday/response.rb:61:in `on_complete'
        /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.10.0/lib/faraday/response.rb:8:in `call'
        /usr/local/lib/ruby/gems/2.3.0/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
        /usr/local/lib/ruby/gems/2.3.0/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:61:in `call'
        /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.10.0/lib/faraday/rack_builder.rb:139:in `build_response'
        /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.10.0/lib/faraday/connection.rb:377:in `run_request'
        /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.10.0/lib/faraday/connection.rb:177:in `patch'
        /usr/local/lib/ruby/gems/2.3.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
        /usr/local/lib/ruby/gems/2.3.0/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
        /usr/local/lib/ruby/gems/2.3.0/gems/octokit-4.6.2/lib/octokit/connection.rb:46:in `patch'
        /usr/local/lib/ruby/gems/2.3.0/gems/octokit-4.6.2/lib/octokit/client/issues.rb:292:in `update_comment'
```

**Comment by davidx** [comment]
fixed in #56
